### ISSUE TITLE
NestJS should be a peer dependency

### ISSUE THREAD

**Issue by karvapallo** [deligenius/aws-sdk-v3-nest#1]
You currently have `@nestjs/common` marked as a dependency, but it should be a peer dependency. 

When marking `@nestjs/common` as a peer dependency, you avoid installing multiple versions of @nestjs/common (which might cause interesting issues) and you also get a warning when trying to install this lib along side an incompatible NestJS version (i.e. in our case v8, who's typings are NOT compatible).

**Comment by gjuoun** [comment]
Sounds good, will update soon

**Comment by gjuoun** [comment]
0.2.0 is out.
https://github.com/deligenius/aws-sdk-v3-nest/releases/tag/0.2.0
