### ISSUE TITLE
Feature Request: Expose utility to create injection provider token

### ISSUE THREAD

**Issue by jayalfredprufrock** [deligenius/aws-sdk-v3-nest#3]
One of the primary reasons for wanting to inject dependencies like AWS clients is for ease of testing. But setting up the testing module requires knowing the dependencies injection provider symbol/token. Since this library constructs it dynamically, there is nothing to import so I had to manually specify `AWS_SDK_V3_MODULE#SESv2Client#` which feels like the library leaking a little too much into my code. 

It would be great to expose a little utility like `getClientToken()` that would generate the string based on the client class you pass in.

**Comment by gjuoun** [comment]
Good idea, it should be like: 

```ts
getClientToken(client: Client, key?:string)

```
also a PR is welcome.

**Comment by gjuoun** [comment]
Done, see [aacb1f0](https://github.com/deligenius/aws-sdk-v3-nest/commit/aacb1f0a5c477576194182a912a156b7047eadbb)
